const UserList = [
	{
		id: "1",
		name: "John Smith",
		userName: "johnsmith23",
		age: 28,
		nationality: "UNITED_STATES",
		friends: [
			{
				id: "2",
				name: "Maria Garcia",
				userName: "mariagarcia",
				age: 24,
				nationality: "SPAIN",
				friends: [], // To avoid circular references in data
			},
			{
				id: "3",
				name: "Hiroshi Tanaka",
				userName: "htanaka",
				age: 32,
				nationality: "JAPAN",
				friends: [],
			},
		],
	},
	{
		id: "2",
		name: "Maria Garcia",
		userName: "mariagarcia",
		age: 24,
		nationality: "SPAIN",
		friends: [
			{
				id: "1",
				name: "John Smith",
				userName: "johnsmith23",
				age: 28,
				nationality: "UNITED_STATES",
				friends: [],
			},
			{
				id: "4",
				name: "Emma Johnson",
				userName: "emmaj_dev",
				age: 27,
				nationality: "UNITED_KINGDOM",
				friends: [],
			},
		],
	},
	{
		id: "3",
		name: "Hiroshi Tanaka",
		userName: "htanaka",
		age: 32,
		nationality: "JAPAN",
		friends: [
			{
				id: "1",
				name: "John Smith",
				userName: "johnsmith23",
				age: 28,
				nationality: "UNITED_STATES",
				friends: [],
			},
		],
	},
	{
		id: "4",
		name: "Emma Johnson",
		userName: "emmaj_dev",
		age: 27,
		nationality: "UNITED_KINGDOM",
		friends: [
			{
				id: "2",
				name: "Maria Garcia",
				userName: "mariagarcia",
				age: 24,
				nationality: "SPAIN",
				friends: [],
			},
			{
				id: "5",
				name: "Pierre Dubois",
				userName: "pierred",
				age: 35,
				nationality: "FRANCE",
				friends: [],
			},
		],
	},
	{
		id: "5",
		name: "Pierre Dubois",
		userName: "pierred",
		age: 35,
		nationality: "FRANCE",
		friends: [
			{
				id: "4",
				name: "Emma Johnson",
				userName: "emmaj_dev",
				age: 27,
				nationality: "UNITED_KINGDOM",
				friends: [],
			},
		],
	},
	{
		id: "6",
		name: "Priya Patel",
		userName: "priyap22",
		age: 26,
		nationality: "INDIA",
		friends: [],
	},
	{
		id: "7",
		name: "Lucas Silva",
		userName: "lucassilva",
		age: 29,
		nationality: "BRAZIL",
		friends: [
			{
				id: "8",
				name: "Anna Mueller",
				userName: "annamueller",
				age: 31,
				nationality: "GERMANY",
				friends: [],
			},
		],
	},
	{
		id: "8",
		name: "Anna Mueller",
		userName: "annamueller",
		age: 31,
		nationality: "GERMANY",
		friends: [
			{
				id: "7",
				name: "Lucas Silva",
				userName: "lucassilva",
				age: 29,
				nationality: "BRAZIL",
				friends: [],
			},
			{
				id: "9",
				name: "Ahmed Hassan",
				userName: "ahmedh",
				age: 33,
				nationality: "EGYPT",
				friends: [],
			},
		],
	},
	{
		id: "9",
		name: "Ahmed Hassan",
		userName: "ahmedh",
		age: 33,
		nationality: "EGYPT",
		friends: [
			{
				id: "8",
				name: "Anna Mueller",
				userName: "annamueller",
				age: 31,
				nationality: "GERMANY",
				friends: [],
			},
		],
	},
	{
		id: "10",
		name: "Sophie Chen",
		userName: "sophiechen",
		age: 25,
		nationality: "CANADA",
		friends: [],
	},
]

const MovieList = [
	{
		id: "1",
		name: "The Quantum Paradox",
		yearOfPublication: 2024,
		isInTheaters: true,
	},
	{
		id: "2",
		name: "Shadows of Tomorrow",
		yearOfPublication: 2023,
		isInTheaters: false,
	},
	{
		id: "3",
		name: "Ocean's Last Stand",
		yearOfPublication: 2024,
		isInTheaters: true,
	},
	{
		id: "4",
		name: "The Silent Revolution",
		yearOfPublication: 2022,
		isInTheaters: false,
	},
	{
		id: "5",
		name: "Neon Dreams",
		yearOfPublication: 2024,
		isInTheaters: true,
	},
	{
		id: "6",
		name: "Beyond the Horizon",
		yearOfPublication: 2023,
		isInTheaters: false,
	},
	{
		id: "7",
		name: "The Last Guardian",
		yearOfPublication: 2024,
		isInTheaters: true,
	},
	{
		id: "8",
		name: "Midnight in Paris 2084",
		yearOfPublication: 2023,
		isInTheaters: false,
	},
	{
		id: "9",
		name: "Echoes of the Past",
		yearOfPublication: 2024,
		isInTheaters: true,
	},
	{
		id: "10",
		name: "The Digital Frontier",
		yearOfPublication: 2022,
		isInTheaters: false,
	},
]

module.exports = { UserList, MovieList }
